# backup/jira_client.py
"""
Mock Jira client – reads data from the JSON file defined in utils.
"""

from typing import Any
from backend.llm_client.models import JiraIssue
from backend.utils import JIRA_ISSUES_FILE, load_json_file, debug_print_env  # noqa: F401

def _load_issue_from_file(key: str) -> JiraIssue:
    """
    Load the whole mock file once, then pick the requested key.
    If the key is missing we return a *fallback* issue so the rest of the
    pipeline can continue (useful for quick demos).
    """
    data: dict[str, Any] = load_json_file(JIRA_ISSUES_FILE)

    raw_issue = data.get(key)
    if raw_issue is None:
        # Fallback – a generic issue that will still be accepted by the LLM
        return JiraIssue(
            key=key,
            summary=f"Mock issue {key}",
            description="Generated by the mock Jira client.",
            acceptance_criteria="The system must generate a test plan.",
        )
    return JiraIssue(**raw_issue)


def get_jira_issue(key: str) -> JiraIssue:
    """Public API used by `main.py`."""
    return _load_issue_from_file(key)